// Generated by CoffeeScript 1.6.2
(function() {
  var resolverFactory, toarray;

  resolverFactory = require("./factory");

  toarray = require("toarray");

  exports.resolve = function(path) {
    return toarray(resolverFactory.create(path).resolve());
  };

}).call(this);
