// Generated by CoffeeScript 1.6.2
(function() {
  var ModuleResolver,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ModuleResolver = (function(_super) {
    __extends(ModuleResolver, _super);

    /*
    */


    function ModuleResolver(_name) {
      this._name = _name;
      ModuleResolver.__super__.constructor.call(this);
    }

    /*
    */


    ModuleResolver.prototype.resolve = function() {
      var _this = this;

      return {
        name: this._name,
        load: function() {
          return require(_this._name);
        }
      };
    };

    /*
    */


    ModuleResolver.create = function(name) {
      return new ModuleResolver(name);
    };

    /*
    */


    ModuleResolver.test = function(name) {
      var e;

      try {
        return require.resolve(name);
      } catch (_error) {
        e = _error;
      }
    };

    return ModuleResolver;

  })(require("./base"));

  module.exports = ModuleResolver;

}).call(this);
